//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CryptoTracker.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Errors {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Errors() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CryptoTracker.Resources.Errors", typeof(Errors).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_HAS_NOT_VERIFIED.
        /// </summary>
        internal static string ACCOUNT_HAS_NOT_VERIFIED {
            get {
                return ResourceManager.GetString("ACCOUNT_HAS_NOT_VERIFIED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_IS_EXISTING.
        /// </summary>
        internal static string ACCOUNT_IS_EXISTING {
            get {
                return ResourceManager.GetString("ACCOUNT_IS_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account is existing.
        /// </summary>
        internal static string ACCOUNT_IS_EXISTING_MSG {
            get {
                return ResourceManager.GetString("ACCOUNT_IS_EXISTING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ACCOUNT_NOT_FOUND.
        /// </summary>
        internal static string ACCOUNT_NOT_FOUND {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account not found.
        /// </summary>
        internal static string ACCOUNT_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("ACCOUNT_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYPTO_WALLET_IS_EXISTING.
        /// </summary>
        internal static string CRYPTO_WALLET_IS_EXISTING {
            get {
                return ResourceManager.GetString("CRYPTO_WALLET_IS_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The crypro wallet is existing.
        /// </summary>
        internal static string CRYPTO_WALLET_IS_EXISTING_MSG {
            get {
                return ResourceManager.GetString("CRYPTO_WALLET_IS_EXISTING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CRYPTO_WALLET_NOT_FOUND.
        /// </summary>
        internal static string CRYPTO_WALLET_NOT_FOUND {
            get {
                return ResourceManager.GetString("CRYPTO_WALLET_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crypto wallet not found.
        /// </summary>
        internal static string CRYPTO_WALLET_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("CRYPTO_WALLET_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY_IS_EXISTING.
        /// </summary>
        internal static string CURRENCY_IS_EXISTING {
            get {
                return ResourceManager.GetString("CURRENCY_IS_EXISTING", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The currency is existing.
        /// </summary>
        internal static string CURRENCY_IS_EXISTING_MSG {
            get {
                return ResourceManager.GetString("CURRENCY_IS_EXISTING_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CURRENCY_NOT_FOUND.
        /// </summary>
        internal static string CURRENCY_NOT_FOUND {
            get {
                return ResourceManager.GetString("CURRENCY_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency not found.
        /// </summary>
        internal static string CURRENCY_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("CURRENCY_NOT_FOUND_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EMAIL_IS_USING_BY_ANOTHER_USER.
        /// </summary>
        internal static string EMAIL_IS_USING_BY_ANOTHER_USER {
            get {
                return ResourceManager.GetString("EMAIL_IS_USING_BY_ANOTHER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This email is used by another user.
        /// </summary>
        internal static string EMAIL_IS_USING_BY_ANOTHER_USER_MSG {
            get {
                return ResourceManager.GetString("EMAIL_IS_USING_BY_ANOTHER_USER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INCORRECT_LOGIN.
        /// </summary>
        internal static string INCORRECT_LOGIN {
            get {
                return ResourceManager.GetString("INCORRECT_LOGIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_INPUT.
        /// </summary>
        internal static string INVALID_INPUT {
            get {
                return ResourceManager.GetString("INVALID_INPUT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INVALID_REQUEST.
        /// </summary>
        internal static string INVALID_REQUEST {
            get {
                return ResourceManager.GetString("INVALID_REQUEST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PHONE_NUMBER_IS_USED_BY_ANOTHER_USER.
        /// </summary>
        internal static string PHONE_NUMBER_IS_USED_BY_ANOTHER_USER {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_IS_USED_BY_ANOTHER_USER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The phone number is used by another user.
        /// </summary>
        internal static string PHONE_NUMBER_IS_USED_BY_ANOTHER_USER_MSG {
            get {
                return ResourceManager.GetString("PHONE_NUMBER_IS_USED_BY_ANOTHER_USER_MSG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WALLET_NOT_FOUND.
        /// </summary>
        internal static string WALLET_NOT_FOUND {
            get {
                return ResourceManager.GetString("WALLET_NOT_FOUND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wallet not found.
        /// </summary>
        internal static string WALLET_NOT_FOUND_MSG {
            get {
                return ResourceManager.GetString("WALLET_NOT_FOUND_MSG", resourceCulture);
            }
        }
    }
}
